In [162]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import random as rd 
 
ds = pd.read_csv("AirQuality.csv", sep=';') 
ds_heart = pd.read_csv("heart.csv", sep=',')

In [163]:
ds_heart

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [164]:
ds.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [165]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   object
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   object
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   object
 13  RH             9357 non-null   object
 14  AH             9357 non-null   object
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(10), object(7)
memory usage: 1.2+ MB

In [166]:
ds.isnull().sum()

Date              114
Time              114
CO(GT)            114
PT08.S1(CO)       114
NMHC(GT)          114
C6H6(GT)          114
PT08.S2(NMHC)     114
NOx(GT)           114
PT08.S3(NOx)      114
NO2(GT)           114
PT08.S4(NO2)      114
PT08.S5(O3)       114
T                 114
RH                114
AH                114
Unnamed: 15      9471
Unnamed: 16      9471
dtype: int64

In [167]:
ds.dropna()

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH, Unnamed: 15, Unnamed: 16]
Index: []

In [168]:
print(ds.columns.tolist())

['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)', 'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16']

In [169]:
ds1 = ds.loc[111:999, ['Date', 'Time', 'C6H6(GT)', 'RH']]

ds2 = ds.iloc[[1,3,5,2,4,22,43,54,67,7,8,9,50,10,11]][['Date', 'Time', 'C6H6(GT)', 'RH']]

ds_integration = pd.concat([ds1, ds2], ignore_index=True)

print(ds_integration)

           Date      Time C6H6(GT)    RH
0    15/03/2004  09.00.00     36,7  54,3
1    15/03/2004  10.00.00     26,6  45,6
2    15/03/2004  11.00.00     20,1  38,5
3    15/03/2004  12.00.00     14,1  34,1
4    15/03/2004  13.00.00     14,9  32,2
..          ...       ...      ...   ...
899  11/03/2004  02.00.00      2,3  59,7
900  11/03/2004  03.00.00      1,7  60,2
901  12/03/2004  20.00.00     32,6  50,5
902  11/03/2004  04.00.00      1,3  60,5
903  11/03/2004  05.00.00      1,1  56,2

[904 rows x 4 columns]

In [170]:
ds_integration.transpose() 
 
ds.drop(columns = "NOx(GT)") 
ds2.drop(1)

          Date      Time C6H6(GT)    RH
3   10/03/2004  21.00.00      9,2  60,0
5   10/03/2004  23.00.00      4,7  59,2
2   10/03/2004  20.00.00      9,0  54,0
4   10/03/2004  22.00.00      6,5  59,6
22  11/03/2004  16.00.00      8,3  71,2
43  12/03/2004  13.00.00     11,0  34,5
54  13/03/2004  00.00.00      9,6  64,1
67  13/03/2004  13.00.00     12,3  31,3
7   11/03/2004  01.00.00      3,3  60,0
8   11/03/2004  02.00.00      2,3  59,7
9   11/03/2004  03.00.00      1,7  60,2
50  12/03/2004  20.00.00     32,6  50,5
10  11/03/2004  04.00.00      1,3  60,5
11  11/03/2004  05.00.00      1,1  56,2

In [171]:
ds.melt()

           variable       value
0              Date  10/03/2004
1              Date  10/03/2004
2              Date  10/03/2004
3              Date  10/03/2004
4              Date  10/03/2004
...             ...         ...
161002  Unnamed: 16         NaN
161003  Unnamed: 16         NaN
161004  Unnamed: 16         NaN
161005  Unnamed: 16         NaN
161006  Unnamed: 16         NaN

[161007 rows x 2 columns]

In [172]:
ds_merged = pd.concat([ds,ds_heart])
ds_merged

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),...,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,241.0,0.0,1.0,123.0,1.0,0.2,1.0,0.0,3.0,0.0
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,264.0,0.0,1.0,132.0,0.0,1.2,1.0,0.0,3.0,0.0
300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,193.0,1.0,1.0,141.0,0.0,3.4,1.0,2.0,3.0,0.0
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,0.0,1.0,115.0,1.0,1.2,1.0,1.0,3.0,0.0
302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,236.0,0.0,0.0,174.0,0.0,0.0,1.0,1.0,2.0,0.0

In [173]:
ds.replace("?", np.nan, inplace=True)

# Convert all columns to numeric
ds=ds.apply(pd.to_numeric, errors='coerce')

In [174]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Separate features and target
X = ds_heart.drop("output", axis=1)
y = ds_heart["output"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LogisticRegression(max_iter=1000)

# Train
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8524590163934426